### ISSUE TITLE
e2e Tests with CI Implementation

### ISSUE THREAD

**Issue by yvesbou** [yvesbou/deposit_erc20#7]
# Motivation
End-to-End (e2e) Tests are a fundamental part of good maintainable code base. It will make sure that the UI behaves correctly. e2e Tests beside the Smart Contract Testing extends the coverage of the whole application.

## Resources
- Cypress (e2e Framework)
- Synpress (Cypress Wrapper for adding Metamask Interaction)
- https://medium.com/p/5248dd1f17c1

## Acceptance Criteria
- [x] The e2e Test covers the login process of the current app
- [ ] The e2e Test is integrated into the CI Pipeline [postponed]

## Todos

- [x] add Cypress
- [x] write Test on Login
- [ ] add e2e to CI [postponed]

**Comment by yvesbou** [comment]
wait for possibility to add CI automation
